# Generated by Django 4.0.4 on 2022-04-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mondayapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('teaching_course', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
