# Generated by Django 4.0.4 on 2022-04-27 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mondayapp', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='client_last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Familiya'),
        ),
        migrations.AddField(
            model_name='application',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mondayapp.course'),
        ),
    ]
