# Generated by Django 4.0.4 on 2022-04-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mondayapp', '0005_alter_application_client_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Client last name'),
        ),
    ]
